all:
  children:
    vms:
      hosts:
        vm1:
        vm2:
        vm3:
    memos:
      children:
        memos_db:
          hosts:
            vm1:
        memos_app:
          hosts:
            vm2:
            vm3:
