- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-requests
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
